### ISSUE TITLE
move this to under https://github.com/worldbank ?

### ISSUE THREAD

**Issue by pythagoraswitch** [worldbank/ml4dev#1]
This repo is in line with reproducible research purpose. More public repos in worldbank account the better :sunglasses: cc: @brunosan @zugaldia

**Comment by brunosan** [comment]
After #2 happens this is properly open MIT code, so anyone is free to fork, clone or move the code :)

We should probably clone and remove this repo to avoid confusion then.

**Comment by pythagoraswitch** [comment]
Since the repo also have text contents, we might want to follow Satellite State of Play practice: "All code is MIT licensed, and the text content is CC-BY."

**Comment by zugaldia** [comment]
@pythagoraswitch 👍 love it.

**Comment by pythagoraswitch** [comment]
@zugaldia I assume :+1: meant I could add the license info, so I just committed the change instead of PR. Feel free to reverse if you don't like the wordings. We will move this repo over to the World Bank account shortly.
