### ISSUE TITLE
google referral URLs

### ISSUE THREAD

**Issue by pythagoraswitch** [worldbank/ml4dev#4]
@zugaldia I see many links are not the direct URLs but google referral URLs. Is there any reasons for this? Is this for analytics purpose?

**Comment by zugaldia** [comment]
@pythagoraswitch Interesting. Where do you see that?

**Comment by pythagoraswitch** [comment]
Many of the URLs in README.md are something like this, instead of direct URL: https://www.google.com/url?q=[URL]&sa=D&usg=[encrypted-jibber-jabbers]

For example, https://github.com/worldbank/ml4dev/edit/master/README.md#L1056
The link to "Data Science from Scratch: First Principles with Python" is https://www.google.com/url?q=http://shop.oreilly.com/product/0636920033400.do&sa=D&usg=AFQjCNENjJbXwVvzp9Sqk-6NPIjwh48WIg

**Comment by zugaldia** [comment]
@pythagoraswitch Good catch. That looks like an oversight, we aren't tracking anything. It's definitely fine to change the URLs to their actual value (http://shop.oreilly.com/product/0636920033400.do in your example).

**Comment by pythagoraswitch** [comment]
@zugaldia sounds good! I just fixed the redirect/referral URLs here d91f1b2

**Comment by zugaldia** [comment]
@pythagoraswitch thank you!
